import Head from "next/head";
import { getProducts } from "../services/products";
import ProductCard from "../components/atoms/productcard";
import Hero from "../components/molecules/hero";

const Home = (products) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero
          size="fullscreen"
          imageUrl="https://images.unsplash.com/photo-1483118714900-540cf339fd46?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
        ></Hero>
        <div className="items-center ">
          <h1 className="text-bold text-5xl text-center pb-10">Productos de Temporada</h1>
        <div className="flex flex-wrap justify-evenly max-w">
          {products.products.map((product) => {
            return (
              <>
                <ProductCard
                  key={product.id}
                  imageUrl={product.image}
                  description={product.description}
                  title={product.title}
                />
              </>
            );
          })}
        </div>
        </div>
      </main>
    </>
  );
};

export const getStaticProps = async () => {
  const data = await getProducts(9);
  return {
    props: { products: data },
  };
};

export default Home;
