import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getProducts } from '../services/products'
import ProductCard from '../components/atoms/ProductCard'

const Home = (products) => {
  console.log(products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Tienda</h1>
        {products.products.map(product => {
          <ProductCard id={product.id}/>
        })}
      </main>
    </>
  )
}

export const getServerSideProps = async()  =>{
  const res = await fetch(`${process.env.API_URL}/products`)
  const data = await res.json()
  console.log(data);
  return {
    props: {products: data}
  }
}

export default Home;